    { "L"          , OPT_EXIT, {show_license},      "show license" },
    { "h"          , OPT_EXIT, { show_help},         "show help", "topic" },
    { "?"          , OPT_EXIT, { show_help},         "show help", "topic" },
    { "help"       , OPT_EXIT, { show_help},         "show help", "topic" },
    { "-help"      , OPT_EXIT, { show_help},         "show help", "topic" },
    { "version"    , OPT_EXIT, { show_version},      "show version" },
    { "buildconf"  , OPT_EXIT, {show_buildconf},    "show build configuration" },
    { "formats"    , OPT_EXIT, {show_formats  },    "show available formats" },
    { "devices"    , OPT_EXIT, {show_devices  },    "show available devices" },
    { "codecs"     , OPT_EXIT, {show_codecs   },    "show available codecs" },
    { "decoders"   , OPT_EXIT, {show_decoders },    "show available decoders" },
    { "encoders"   , OPT_EXIT, {show_encoders },    "show available encoders" },
    { "bsfs"       , OPT_EXIT, {show_bsfs     },    "show available bit stream filters" },
    { "protocols"  , OPT_EXIT, {show_protocols},    "show available protocols" },
    { "filters"    , OPT_EXIT, {show_filters  },    "show available filters" },
    { "pix_fmts"   , OPT_EXIT, {show_pix_fmts },    "show available pixel formats" },
    { "layouts"    , OPT_EXIT, {show_layouts  },    "show standard channel layouts" },
    { "sample_fmts", OPT_EXIT, {show_sample_fmts }, "show available audio sample formats" },
    { "colors"     , OPT_EXIT, {show_colors },      "show available color names" },
    { "loglevel"   , HAS_ARG,  {opt_loglevel},      "set logging level", "loglevel" },
    { "v",           HAS_ARG,  {opt_loglevel},      "set logging level", "loglevel" },
    { "report"     , 0,        {(void*)opt_report}, "generate a report" },
    { "max_alloc"  , HAS_ARG,  {opt_max_alloc},     "set maximum size of a single allocated block", "bytes" },
    { "cpuflags"   , HAS_ARG | OPT_EXPERT, { opt_cpuflags }, "force specific cpu flags", "flags" },
    { "hide_banner", OPT_BOOL | OPT_EXPERT, {&hide_banner},     "do not show program banner", "hide_banner" },
#if CONFIG_OPENCL
    { "opencl_bench", OPT_EXIT, {opt_opencl_bench}, "run benchmark on all OpenCL devices and show results" },
    { "opencl_options", HAS_ARG, {opt_opencl},      "set OpenCL environment options" },
#endif
#if CONFIG_AVDEVICE
    { "sources"    , OPT_EXIT | HAS_ARG, { show_sources },
      "list sources of the input device", "device" },
    { "sinks"      , OPT_EXIT | HAS_ARG, { show_sinks },
      "list sinks of the output device", "device" },
#endif
